[package]
edition = "2021"
name = "bkmrk"
version = "0.1.0"

[dependencies]
clap = "2.34"
console = "0.15"
dialoguer = "0.9"
fern = "0.6"
simple-error = "0.2"
tabled = "0.4"
terminal_size = "0.1"
log = "0.4"
bkmrk-lib = { path = "./bkmrk-lib", features = ["tables"] }
chrono = "0.4"
